# Generated by Django 6.0.6 on 2026-07-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_department_programme_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.department'),
        ),
    ]
