# Generated by Django 6.0.6 on 2026-07-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_is_active_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-year_name'], 'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Years'},
        ),
        migrations.AlterModelOptions(
            name='intake',
            options={'ordering': ['-academic_year__year_name', 'start_date'], 'verbose_name': 'Intake', 'verbose_name_plural': 'Intakes'},
        ),
    ]
