# Generated by Django 6.0.6 on 2026-07-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_registration_drop_reason_registration_dropped_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_offerings', to='students.academicyear')),
                ('programme_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_offerings', to='students.programmelevel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_offerings', to='students.semester')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='students.unit')),
            ],
            options={
                'ordering': ['unit__code'],
                'unique_together': {('academic_year', 'semester', 'unit', 'programme_level')},
            },
        ),
    ]
