# Generated by Django 6.0.6 on 2026-07-25 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_unitoffering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerassignment',
            options={'ordering': ['-unit_offering__academic_year__year_name', 'unit_offering__semester__semester_name', 'unit_offering__programme_level__progression_order', 'unit_offering__unit__code'], 'verbose_name': 'Lecturer Assignment', 'verbose_name_plural': 'Lecturer Assignments'},
        ),
        migrations.AlterUniqueTogether(
            name='lecturerassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lecturerassignment',
            name='unit_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_assignments', to='students.unitoffering'),
        ),
        migrations.AlterField(
            model_name='lecturerassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lecturer_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturerassignment',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Lecturer'}, on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='lecturerassignment',
            constraint=models.UniqueConstraint(fields=('lecturer', 'unit_offering'), name='unique_lecturer_unit_offering'),
        ),
        migrations.RemoveField(
            model_name='lecturerassignment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='lecturerassignment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lecturerassignment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='lecturerassignment',
            name='unit',
        ),
    ]
