# Generated by Django 6.0.6 on 2026-07-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='students.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'semester_name'],
                'unique_together': {('academic_year', 'semester_name')},
            },
        ),
    ]
