# Generated by Django 6.0.6 on 2026-07-09 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('credit_hours', models.PositiveIntegerField(default=0)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='students.programme')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='students.semester')),
            ],
        ),
    ]
