# Generated by Django 6.0.6 on 2026-07-09 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20, unique=True)),
                ('unit_name', models.CharField(max_length=200)),
                ('credit_hours', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='students.course')),
            ],
            options={
                'ordering': ['unit_code'],
            },
        ),
    ]
