# Generated by Django 6.0.6 on 2026-07-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='students.academicyear')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='students.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='students.unit')),
            ],
            options={
                'ordering': ['-registration_date'],
                'unique_together': {('student', 'academic_year', 'semester', 'unit')},
            },
        ),
    ]
