# Generated by Django 6.0.6 on 2026-07-28 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_resultbatch_published_at_resultbatch_published_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROMOTED', 'Promoted'), ('COMPLETED', 'Completed Programme'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progression_from_logs', to='students.semesterenrollment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progression_logs', to='students.student')),
                ('to_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progression_to_logs', to='students.semesterenrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
