# Generated by Django 6.0.6 on 2026-07-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
