# Generated by Django 6.0.6 on 2026-07-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_semester_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_levels', to='students.programme')),
            ],
            options={
                'ordering': ['programme', 'level_name'],
                'unique_together': {('programme', 'level_name')},
            },
        ),
    ]
