# Generated by Django 6.0.6 on 2026-07-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_studylevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['programme', 'study_level', 'semester', 'course_code']},
        ),
        migrations.AddField(
            model_name='course',
            name='study_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='students.studylevel'),
        ),
    ]
