# Generated by Django 6.0.6 on 2026-07-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_course_options_course_study_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='study_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.studylevel'),
        ),
    ]
