# Generated by Django 6.0.6 on 2026-07-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_study_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studylevel',
            options={'ordering': ['id'], 'verbose_name': 'Study Level', 'verbose_name_plural': 'Study Levels'},
        ),
        migrations.AlterUniqueTogether(
            name='studylevel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studylevel',
            name='level_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='studylevel',
            name='programme',
        ),
    ]
