# Generated by Django 6.0.6 on 2026-07-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_studylevel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('deferred', 'Deferred'), ('suspended', 'Suspended'), ('completed', 'Completed')], default='enrolled', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.academicyear')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('study_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.studylevel')),
            ],
            options={
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
    ]
