# Generated by Django 6.0.6 on 2026-07-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_semesterenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterenrollment',
            options={},
        ),
        migrations.AddField(
            model_name='registration',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='students.semesterenrollment'),
        ),
    ]
