# Generated by Django 6.0.6 on 2026-07-10 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_semesterenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('enrollment', 'unit')},
        ),
        migrations.AlterField(
            model_name='registration',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='students.semesterenrollment'),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
    ]
