# Generated by Django 6.0.6 on 2026-07-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_record', to='students.student'),
        ),
    ]
