# Generated by Django 6.0.6 on 2026-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_applicant_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-application_date', '-id'], 'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AddField(
            model_name='applicant',
            name='application_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
