# Generated by Django 6.0.6 on 2026-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_applicant_options_applicant_application_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
