# Generated by Django 6.0.6 on 2026-07-10 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='intake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='students.intake'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='students.academicyear'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='students.programme'),
        ),
    ]
