# Generated by Django 6.0.6 on 2026-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_applicant_intake_alter_applicant_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['admission_no']},
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
