# Generated by Django 6.0.6 on 2026-07-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='lecturer_no',
        ),
    ]
