# Generated by Django 6.0.6 on 2026-07-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_remove_lecturer_first_name_remove_lecturer_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
