# Generated by Django 6.0.6 on 2026-07-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_resultbatch_result_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned'), ('unlocked', 'Unlocked')], default='draft', max_length=20),
        ),
    ]
