# Generated by Django 6.0.6 on 2026-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_resultbatchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylevel',
            name='is_final_level',
            field=models.BooleanField(default=False, help_text='Tick if this is the final study level for graduation.'),
        ),
    ]
