# Generated by Django 6.0.6 on 2026-07-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_studylevel_is_final_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studylevel',
            name='is_final_level',
        ),
    ]
