# Generated by Django 6.0.6 on 2026-07-31 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('Admissions', 'Admissions'), ('Students', 'Students'), ('Registration', 'Registration'), ('Enrollment', 'Enrollment'), ('Finance', 'Finance'), ('Academics', 'Academics'), ('Transcript', 'Transcript'), ('Graduation', 'Graduation'), ('System', 'System')], db_index=True, max_length=30)),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Approve', 'Approve'), ('Reject', 'Reject'), ('Login', 'Login'), ('Logout', 'Logout'), ('Generate', 'Generate'), ('Print', 'Print')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Critical', 'Critical')], db_index=True, default='Info', max_length=10)),
                ('description', models.TextField()),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='system_acti_module_1c7b2b_idx'), models.Index(fields=['action', 'created_at'], name='system_acti_action_c4d255_idx'), models.Index(fields=['severity', 'created_at'], name='system_acti_severit_abeb7e_idx')],
            },
        ),
    ]
