# Generated by Django 6.0.6 on 2026-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'default_permissions': ('view',), 'ordering': ['-created_at'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='record_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('Admissions', 'Admissions'), ('Students', 'Students'), ('Registration', 'Registration'), ('Enrollment', 'Enrollment'), ('Semester Enrollment', 'Semester Enrollment'), ('Finance', 'Finance'), ('Academics', 'Academics'), ('Transcript', 'Transcript'), ('Graduation', 'Graduation'), ('System', 'System')], db_index=True, max_length=30),
        ),
    ]
