# Generated by Django 6.0.6 on 2026-07-22 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fee Category',
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_registration_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('minimum_exam_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('minimum_result_slip_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('minimum_transcript_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('minimum_graduation_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('allow_overpayment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finance Setting',
                'verbose_name_plural': 'Finance Settings',
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='students.academicyear')),
                ('programme_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='students.programmelevel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='students.semester')),
            ],
            options={
                'ordering': ['programme_level', 'academic_year', 'semester'],
                'unique_together': {('programme_level', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='FinancialClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_cleared', models.BooleanField(default=False)),
                ('exam_cleared', models.BooleanField(default=False)),
                ('result_slip_cleared', models.BooleanField(default=False)),
                ('transcript_cleared', models.BooleanField(default=False)),
                ('graduation_cleared', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_clearance', to='students.semesterenrollment')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('MPESA', 'MPESA'), ('BANK', 'Bank'), ('CASH', 'Cash')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('posting_status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=20)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='finance.payment')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='finance.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('credit_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='students.semesterenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.student')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.studentinvoice'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.studentinvoice')),
            ],
            options={
                'ordering': ['fee_category'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feecategory')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.feestructure')),
            ],
            options={
                'ordering': ['fee_category'],
                'constraints': [models.UniqueConstraint(fields=('fee_structure', 'fee_category'), name='unique_fee_structure_item')],
            },
        ),
    ]
