# Generated by Django 6.0.6 on 2026-07-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feestructure_feestructureitem'),
        ('students', '0035_resultbatchlog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('programme', 'academic_year', 'semester', 'study_level'), name='unique_fee_structure'),
        ),
    ]
