# Generated by Django 6.0.6 on 2026-07-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_feestructure_unique_fee_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='name',
        ),
    ]
