# Generated by Django 6.0.6 on 2026-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payment_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvoice',
            name='amount_paid_cached',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='balance_cached',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='invoice_total',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
