# Generated by Django 6.0.6 on 2026-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
