# Generated by Django 6.0.6 on 2026-07-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_registration_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('minimum_exam_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('minimum_result_slip_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('minimum_transcript_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('minimum_graduation_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('allow_overpayment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finance Setting',
                'verbose_name_plural': 'Finance Settings',
            },
        ),
    ]
