# Generated by Django 6.0.6 on 2026-07-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_financialclearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialclearance',
            name='exam_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialclearance',
            name='graduation_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialclearance',
            name='registration_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialclearance',
            name='result_slip_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialclearance',
            name='transcript_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
