# Generated by Django 6.0.6 on 2026-07-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_financialclearance_exam_cleared_and_more'),
        ('students', '0035_resultbatchlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='finance.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='students.student')),
            ],
        ),
    ]
