# Generated by Django 6.0.6 on 2026-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_studentcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvoice',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
