# Generated by Django 6.1.1 on 2026-09-29 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_message_messagethread_and_more'),
        ('students', '0014_department_hod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('ALL', 'All Students'), ('DEPARTMENT', 'Department'), ('PROGRAMME', 'Programme'), ('STUDENT', 'Individual Student')], db_index=True, default='ALL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description shown to students before they open the form.')),
                ('google_form_url', models.URLField(help_text='Paste the Google Forms URL here.', max_length=1000)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_student_feedback_forms', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_targets', to='students.department')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_targets', to='students.programme')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='students.student')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='communicati_is_publ_40e07f_idx'), models.Index(fields=['audience', 'closes_at'], name='communicati_audienc_43995d_idx')],
            },
        ),
    ]
