# Generated by Django 6.0.6 on 2026-07-22 02:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField(default=django.utils.timezone.now)),
                ('certificate_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ELIGIBLE', 'Eligible'), ('APPROVED', 'Approved'), ('GRADUATED', 'Graduated')], default='PENDING', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduations', to='students.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_graduations', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to='students.student')),
            ],
            options={
                'verbose_name': 'Graduation',
                'verbose_name_plural': 'Graduations',
                'ordering': ['-graduation_date', 'student__admission_no'],
            },
        ),
    ]
