# Generated by Django 6.0.6 on 2026-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='classification',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='graduation',
            name='overall_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
